### ISSUE TITLE
Convergence problem

### ISSUE THREAD

**Issue by haniees** [mhahsler/pomdp#11]
Hi,

I have a finite horizon problem that is not converging. I read in the manual that I should put the initial value function of zero in order to guarantee the convergence. Where can I add this to the code? should I add it in here?
sol <- solve_POMDP(model = Total, discount = 0.99, method = "grid")
if yes how?

Thanks

**Comment by mhahsler** [comment]
Hi, please share the code to create the model.

**Comment by mhahsler** [comment]
Please send me the code and data for Total again.
